import { createActions } from 'reduxsauce';

export const { Types, Creators } = createActions({
	// Notification
	setNotification: ['message', 'level'],
	clearNotification: null,
	// Auth & User
	loginAttempt: ['user'],
	loginAuthSuccess: ['auth'],
	loginUserSuccess: ['user', 'success'],
	loginFailure: ['error'],
	logout: null,
	getUsersAttempt: null,
	getUsersSuccess: ['data'],
	getUsersFailure: null,
	registerAttempt: ['user'],
	registerSuccess: ['user', 'success'],
	registerFailure: ['error'],
	setSubscriptionType: ['data'],
	setAppointment: ['value'],
	bookingSuccess: ['booking', 'success'],
	bookingFailure: ['error'],
	getAppointmentRequest: null,
	getAppointmentSuccess: ['appointments', 'success'],
	getAppointmentFailed: ['error'],
	updateAppointmentStatusRequest: ['data'],
	updateAppointmentStatusSuccess: ['appointment', 'success'],
	updateAppointmentStatusFailed: ['error'],
	getUsersRequest: null,
	getUsersSuccess: ['users', 'success'],
	getUsersFailed: ['error'],
	getUserInfoRequest: ['userId'],
	getUserInfoSuccess: ['user', 'success'],
	getUserInfoFailed: ['error'],
	updateUserInfoRequest: ['data', 'userId'],
	updateUserInfoSuccess: ['user', 'success'],
	updateUserInfoFailed: ['error'],
	pickDate: ['data'],
	getBookingDatesRequest: null,
	getBookingDatesSuccess: ['bookings', 'success'],
	getBookingDatesFailed: ['error'],

})
